name: stock_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - yfinance
  - python-dotenv
  - requests
  - plotly
  - dash
  - sentence-transformers
  - faiss-cpu
  - pytorch
  - dash[diskcache]
  - pandas-ta
